/**
 * Setup Server
 * Minimal web server for setup wizard when config is invalid/missing
 */

import { loadConfigSafe, getConfigSchema } from "../config.ts";
import indexHtml from "./public/index.html";

let server: ReturnType<typeof Bun.serve> | null = null;

/**
 * Generate .env file content from form data
 */
function generateEnvFile(formData: Record<string, string>): string {
  const lines: string[] = [
    "# Cobrain Configuration",
    "# Generated by Setup Wizard",
    "",
    "# === Required ===",
  ];

  // Required fields
  if (formData.TELEGRAM_BOT_TOKEN) {
    lines.push(`TELEGRAM_BOT_TOKEN=${formData.TELEGRAM_BOT_TOKEN}`);
  }
  if (formData.MY_TELEGRAM_ID) {
    lines.push(`MY_TELEGRAM_ID=${formData.MY_TELEGRAM_ID}`);
  }

  lines.push("", "# === Optional ===");

  // Optional fields with defaults
  const optionalFields = [
    { key: "GEMINI_API_KEY", default: "" },
    { key: "WEB_PORT", default: "3000" },
    { key: "AGENT_MODEL", default: "claude-opus-4-6" },
    { key: "MAX_HISTORY", default: "10" },
    { key: "ENABLE_AUTONOMOUS", default: "true" },
    { key: "PERMISSION_MODE", default: "smart" },
    { key: "ENABLE_WEB_UI", default: "true" },
    { key: "ENABLE_HEARTBEAT_MONITORING", default: "true" },
  ];

  for (const field of optionalFields) {
    const value = formData[field.key] || field.default;
    if (value) {
      lines.push(`${field.key}=${value}`);
    }
  }

  return lines.join("\n") + "\n";
}

/**
 * Load existing .env values if file exists but is invalid
 */
async function loadExistingEnv(): Promise<Record<string, string>> {
  try {
    const envFile = Bun.file(".env");
    if (await envFile.exists()) {
      const content = await envFile.text();
      const values: Record<string, string> = {};

      for (const line of content.split("\n")) {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith("#")) {
          const [key, ...valueParts] = trimmed.split("=");
          if (key) {
            values[key] = valueParts.join("=");
          }
        }
      }

      return values;
    }
  } catch {
    // Ignore errors
  }
  return {};
}

/**
 * Start the setup server
 */
export function startSetupServer(): void {
  if (server) {
    console.warn("[Setup] Server already running");
    return;
  }

  // Port from env or default 3000
  const PORT = parseInt(process.env.WEB_PORT || "3000", 10);

  server = Bun.serve({
    port: PORT,

    routes: {
      // Serve index.html for root
      "/": indexHtml,

      // Health check
      "/health": () => new Response("OK"),

      // API: Get setup status and schema
      "/api/setup/status": async () => {
        const configResult = loadConfigSafe();
        const existingValues = await loadExistingEnv();

        return Response.json({
          setupRequired: !configResult.success,
          errors: configResult.success ? [] : configResult.errors,
          schema: getConfigSchema(),
          existingValues,
        });
      },

      // API: Save configuration
      "/api/setup/save": async (req) => {
        if (req.method !== "POST") {
          return new Response("Method not allowed", { status: 405 });
        }

        try {
          const formData = (await req.json()) as Record<string, string>;

          // Validate required fields
          if (!formData.TELEGRAM_BOT_TOKEN) {
            return Response.json(
              { success: false, error: "Telegram Bot Token is required" },
              { status: 400 }
            );
          }

          if (!formData.MY_TELEGRAM_ID) {
            return Response.json(
              { success: false, error: "Telegram User ID is required" },
              { status: 400 }
            );
          }

          // Generate and save .env file
          const envContent = generateEnvFile(formData);

          try {
            await Bun.write(".env", envContent);
          } catch (err) {
            console.error("[Setup] Failed to write .env:", err);
            return Response.json(
              {
                success: false,
                error:
                  "Failed to write file. You may need to create the .env file manually.",
                manualContent: envContent,
              },
              { status: 500 }
            );
          }

          return Response.json({ success: true });
        } catch (err) {
          console.error("[Setup] Save error:", err);
          return Response.json(
            { success: false, error: "Invalid request" },
            { status: 400 }
          );
        }
      },

      // API: Restart application
      "/api/setup/restart": async (req) => {
        if (req.method !== "POST") {
          return new Response("Method not allowed", { status: 405 });
        }

        // Schedule restart after response
        setTimeout(() => {
          console.log("[Setup] Restarting application...");
          // Use cobrain-restart command
          Bun.spawn(["cobrain-restart"], {
            stdout: "inherit",
            stderr: "inherit",
          });
        }, 1000);

        return Response.json({ success: true, message: "Restarting..." });
      },
    },

    // Handle other requests
    fetch() {
      return new Response("Not Found", { status: 404 });
    },

    // Development options
    development:
      process.env.NODE_ENV !== "production"
        ? {
            hmr: true,
            console: true,
          }
        : false,
  });

  console.log(`[Setup] Server started on http://localhost:${PORT}`);
}

/**
 * Stop the setup server
 */
export function stopSetupServer(): void {
  if (server) {
    server.stop();
    server = null;
    console.log("[Setup] Server stopped");
  }
}
